### ISSUE TITLE
Can't open from Navicat 

### ISSUE THREAD

**Issue by MrLibya** [devbean/QtCipherSqlitePlugin#11]
I've compiled the plugin and evrything is ok 👍 
so i've create new Sqlite3 DB from navicat and uses encrypt option : [img](https://image.prntscr.com/image/67901c3a5ce94a28aee7f20d71b7b19a.png) , Navicat uses wxSQLite3 for encrypt, but when i try to login from Qt to the database it says : `Can not open connection:  "Invalid password"`

so i've change the db name to another name(non-exist db):`QString DB_FILE_PATH = dir + "/test_new.db";`
and `dbconn.setPassword("gogo");`

he did make a new DB called test_new , and evrything work find : [img](https://image.prntscr.com/image/a9f7c61656d343df9d4bebbd9e5a963b.png)

but when i try to connect to this db from navicat and i've put the encrypt password (gogo) it says : [img](https://image.prntscr.com/image/dd4bfaee2f1f47a097bd8b6e49d3b4d0.png) , that's haapens when the password is incorrect !

so what is the problem ? i've also try to use only numbers but same problem !

**Comment by devbean** [comment]
Please check which encrypt algorithm Navicat use. I googled Navicat uses wxSQLite3 (128-bit AES) for SQLite encryption while QtCipherSqlitePlugin uses AES-256 by default. In order to use AES-128, change `CODEC_TYPE` to `CODEC_TYPE_AES128` in `DEFINES` in sqlitecipher/sqlite3/sqlite3.pri. Please let me know if this works.

**Comment by MrLibya** [comment]
Yes it's work , thx :)
